//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BY_1._2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BYEntities1 : DbContext
    {
        public BYEntities1()
            : base("name=BYEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Experience> Experiences { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Personal_info> Personal_info { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Summary> Summaries { get; set; }
        public virtual DbSet<Userr> Userrs { get; set; }
    }
}
